services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgresbitinami
      - POSTGRES_PASSWORD=postgresbitinamipass
      - POSTGRES_DB=mediumclone_nestjs
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    networks:
      - postgresql_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgresql_data:
    driver: local

networks:
  postgresql_network:
    driver: bridge