services:
  postgres:
    container_name: nest-with-prisma-pg
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres_docker
      POSTGRES_PASSWORD: password_docker
      POSTGRES_DB: mediumclone_nestjs
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

volumes:
  postgres_data: