@baseUrl = http://localhost:8080/api

@authToken =

# @name Registrar Usuário
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
  "user":{
    "username": "janeDoe",
    "email": "janedoe@email.com",
    "password": "janeDoe123"
  }
}

###