@baseUrl = http://localhost:8080/api

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ODU3ODIxMi1jODA3LTRhODUtOTYzMy01NWU0YWNmMWZmZGQiLCJpYXQiOjE3MjQ3MTM3NTMsImV4cCI6MTcyNDcxNzM1M30.uJzOe4LGM0vxWGNdAGEOEu2ncCjkg2rK_mVXHycEGpc

# @name Registrar Usuário
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
  "user":{
    "username": "janeDoe",
    "email": "janedoe@email.com",
    "password": "janeDoe123"
  }
}

###

# @name Obter Usuário Atual
GET {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###

# @name Atualizar Usuário
PUT {{baseUrl}}/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "user":{
    "username": "jane-Doe",
    "email": "janedoe@email.com",
    "password": "janeDoe1234",
    "bio": "Desenvolvedor freelancer",
    "image": ""
  }
}